### PR TITLE
WIP: Add task runner tutorial

### PR DESCRIPTION
**Pull request by whitneyit**
Re: #1

### CODE REVIEW

**Comment by whitneyit** [comment]
In regards to my final point in #1, do you want to create a repo for the task runner implenetstions of these?

**Comment by ishubin** [comment]
Your change is now live. Thanks a lot for your support! Yes, I think it is a great idea. I have created a repo as you suggested https://github.com/galenframework/samples-task-runners. I only added a prefix "samples" to it as in future there might be more similar projects.

**Comment by whitneyit** [comment]
Its awesome to have my support appreciated :smile: I'll make the relevant
changes via a PR to the new repo and then I'll update the post accordingly

**Comment by ishubin** [comment]
I have implemented a hacky way of authoring the articles. For now you have to specify authorName and authorLink for each article. But soon I will try to get some time to implement this author support in blogix

**Comment by whitneyit** [comment]
That sounds great! Do you also want to keep the blockquote at the top of
the page?

**Comment by ishubin** [comment]
Sure, I think it is also a good idea. As for me it works even better. I would prefer to make it obvious that this article was written by you so that people ask you questions instead of me ;)

**Comment by whitneyit** [comment]
Haha. Ok mate cheers

**Comment by whitneyit** [comment]
Did you perhaps have anything to do with the [gallen packages](https://www.npmjs.com/~fer3) that are published to npm.?

There seems to be some code hosted at https://github.com/fer3/galen I haven't tried contacting fer3 yet.

**Comment by ishubin** [comment]
No, I didn't know anything about this

**Comment by whitneyit** [comment]
Re: fer3/galen#1

**Comment by whitneyit** [comment]
I'll update the tutorial to take into account usage with gulp and then link to https://github.com/galenframework/samples-task-runners.

Would I be able to get write access to that repo if that's cool?

**Comment by ishubin** [comment]
Hi @whitneyit ! Sure I have added to to that repo as a collaborator. Let me know if it doesn't work for you

**Comment by whitneyit** [comment]
Awesome man cheers! I'll start on it when I get to work.

Thanks

**Pull request merged**
